# Generated by Django 4.1.1 on 2022-09-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UsersID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('mail', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
