# Generated by Django 4.1.3 on 2022-11-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsersID', models.CharField(max_length=500)),
                ('Registradopor', models.CharField(max_length=500)),
                ('Ocurrencias', models.CharField(max_length=500)),
                ('Departamento', models.CharField(max_length=500)),
                ('Municipio', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
