# Generated by Django 4.1.3 on 2022-11-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_especimen_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Especimen',
        ),
    ]
