# Generated by Django 4.1.3 on 2022-11-21 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_especimen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroCatalogo', models.CharField(max_length=500)),
                ('NombreDelConjuntoDatos', models.CharField(max_length=500)),
                ('ComentarioRegistroBiologico', models.CharField(max_length=500)),
                ('RegistradoPor', models.CharField(max_length=500)),
                ('NumeroIndividuo', models.IntegerField()),
                ('FechaEvento', models.DateTimeField()),
                ('Habitad', models.CharField(max_length=500)),
                ('Departamento', models.CharField(max_length=500)),
                ('Municipio', models.CharField(max_length=500)),
                ('IdentificadoPor', models.CharField(max_length=500)),
                ('FechaIdentificacion', models.DateTimeField()),
                ('IdentificacionReferencias', models.CharField(max_length=500)),
                ('ComentarioIdentificacion', models.CharField(max_length=500)),
                ('NombreCientificoComentarioRegistroBiologico', models.CharField(max_length=500)),
                ('NombreComun', models.CharField(max_length=500)),
                ('Clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clase')),
            ],
        ),
    ]
