# Generated by Django 4.1.3 on 2022-11-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_especimen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especimen',
            new_name='Ejemplar',
        ),
    ]
